# Generated by Django 5.1.4 on 2025-02-07 10:50

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cercles',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Shp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='sigweb.cercle')),
            ],
            options={
                'db_table': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='Douar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='sigweb.commune')),
            ],
            options={
                'db_table': 'Douars',
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dossie', models.CharField(blank=True, max_length=255)),
                ('num_parcel', models.CharField(blank=True, max_length=255)),
                ('consistanc', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('nb_de_faca', models.IntegerField()),
                ('fchier_dwg', models.FileField(blank=True, null=True, upload_to='dwg/')),
                ('fchier_pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('douar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='sigweb.douar')),
            ],
            options={
                'db_table': 'Parcelles',
            },
        ),
        migrations.AddField(
            model_name='cercle',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cercles', to='sigweb.province'),
        ),
    ]
