# Generated by Django 5.1.4 on 2025-02-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='douar',
            name='id',
        ),
        migrations.AlterField(
            model_name='douar',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
