# Generated by Django 5.1.4 on 2025-02-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigweb', '0002_remove_douar_id_alter_douar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cercle',
            name='province',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='cercle',
        ),
        migrations.RemoveField(
            model_name='douar',
            name='commune',
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='douar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='cercle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='commune',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='province',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Cercle',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Douar',
        ),
    ]
