# Generated by Django 5.1.4 on 2025-02-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigweb', '0004_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to='sigweb.parcelle'),
        ),
    ]
